export const PROJECT_SUPERPOWERS_SKILL_CONTENT: Record<string, string> = {
  'using-superpowers': [
    '---',
    'name: using-superpowers',
    'description: Use when starting any conversation - establishes how to find and use skills, requiring skill invocation before any response including clarifying questions',
    '---',
    '',
    '# Using Superpowers',
    '',
    'You have superpowers. Before responding, decide whether any skill applies.',
    '',
    '## The Rule',
    '',
    '**Invoke relevant or requested skills BEFORE any response or action.** Even a 1% chance a skill might apply means that you should invoke the skill to check. If an invoked skill turns out to be wrong for the situation, you do not need to use it.',
    '',
    '## Project-Owned Adaptation',
    '',
    'In OpenDeepSea project-owned mode, use the project-builtin Superpowers skill blocks already loaded in the prompt as the source of truth.',
    '',
    'Do not load same-name skills from local user paths such as ~/.agents/skills, ~/.codex/skills, or ~/.codex/superpowers.',
    '',
    'ACP filesystem, search, and shell tools remain available according to the current agent runtime permission policy.',
    '',
    '## Skill Priority',
    '',
    '1. Process skills first, such as brainstorming and systematic debugging.',
    '2. Implementation skills second, such as writing-plans, TDD, execution, review, and verification.',
    '',
    'For feature requests or behavior changes, use brainstorming before implementation planning.',
  ].join('\n'),
  brainstorming: [
    '---',
    'name: brainstorming',
    'description: You MUST use this before any creative work - creating features, building components, adding functionality, or modifying behavior.',
    '---',
    '',
    '# Brainstorming Ideas Into Designs',
    '',
    'Help turn ideas into fully formed designs and specs through natural collaborative dialogue.',
    '',
    'Start by understanding the current project context, then ask questions one at a time to refine the idea. Once you understand what is being built, present the design and get user approval.',
    '',
    '## Hard Gate',
    '',
    'Do not write code, scaffold projects, or take implementation actions until a design has been presented and approved. For explicit read-only requests, stop at brief clarification and do not modify files.',
    '',
    '## Checklist',
    '',
    '1. Explore project context.',
    '2. Ask clarifying questions one at a time.',
    '3. Propose 2-3 approaches with trade-offs and a recommendation.',
    '4. Present a design scaled to the task.',
    '5. After approval, transition to writing-plans for implementation planning.',
    '',
    '## Working in Existing Codebases',
    '',
    'Follow existing patterns, keep scope focused, and avoid unrelated refactoring. If the request is small, produce a concise design and one clear next question.',
    '',
    '## Key Principles',
    '',
    '- Understand purpose, constraints, success criteria, and boundaries.',
    '- Prefer multiple-choice clarification when useful.',
    '- Be explicit about whether a request should enter workflow or remain a lightweight discussion.',
    '- Do not depend on local user-installed skills in project-owned mode.',
  ].join('\n'),
};
